export * from './BigQuestLogoIcon';
export * from './DownloadPhotoIcon';
export * from './FullLogoIcon';
export * from './LogoIcon';
export * from './RhombIcon';
export * from './TelegramIcon';
export * from './VkIcon';
export * from './WavyLineIcon';
export * from './WhatsappIcon';
