#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git symbolic-ref --short HEAD)
message=$(cat "$1")

if [ -f .emoji ]; then
  emoji=$(cat .emoji)

  if echo "$message" | (! grep -q "^Merge branch*") && echo "$message" | (! grep -q "^${branch} ${emoji}*"); then
    echo "$branch $emoji $message" > "$1"
  fi
else 
  echo "$message"
fi